apiVersion: apps/v1
kind: Deployment
metadata:
  name: appjava-deployment
spec:
  selector:
    matchLabels:
      app: appjava
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: appjava
    spec:
      containers:
      - name: appjava
        image: lucaseveron/appjava:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        envFrom:
        - secretRef:
            name: my-secret
      volumes:
      - name: data-volume
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: appjava-service
spec:
  selector:
    app: appjava
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appjava-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appjava-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: myconfigmap

